version: '3.9'

services:
  emqx-instance-1:
    image: emqx/emqx:${EMQX_VERSION}
    container_name: emqx-instance-1
    hostname: e1.emqx-cluster.com
    restart: on-failure

    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"

    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io

    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"

  emqx-instance-2:
    image: emqx/emqx:${EMQX_VERSION}
    container_name: emqx-instance-2
    hostname: e2.emqx-cluster.com
    restart: on-failure

    environment:
      - "EMQX_NODE_NAME=emqx@node2.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"

    networks:
      emqx-bridge:
        aliases:
          - node2.emqx.io

networks:
  emqx-bridge:
    driver: bridge

